# Generated by Django 4.1.7 on 2023-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AddField(
            model_name='role',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='position'),
        ),
    ]
