# Generated by Django 4.1.7 on 2023-05-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_options_role_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, upload_to='user_pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('OBS', 'Observer'), ('MNG', 'Manager'), ('ADM', 'Administrator')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
