# Generated by Django 4.1.7 on 2023-05-28 08:43

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_staff_user_alter_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='user',
            name='loyaltyCard',
            field=models.CharField(default=0, max_length=10, verbose_name='Loyalty card'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='Money'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='patronymic'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Member'), ('2', 'Observer'), ('3', 'Manager'), ('4', 'Administrator')], default='1', max_length=1, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='visibleformembers',
            field=models.BooleanField(default=True, verbose_name='visible for members'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visibleforchat',
            field=models.BooleanField(default=True, verbose_name='visible for chat'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
