# Generated by Django 4.1.7 on 2023-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_pic_user_avatar_remove_user_roles_user_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyaltyCard',
            field=models.CharField(default=13, max_length=10, verbose_name='Loyalty card'),
        ),
    ]
