# Generated by Django 4.1.7 on 2023-05-23 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Room',
        ),
    ]
